### ISSUE TITLE
invalid operation: channel.Type == "text" (mismatched types discordgo.ChannelType and string)

### ISSUE THREAD

**Issue by spencer1573** [dhedegaard/notibot#1]
when I try to run the main part of the app I get these errors,
I'm really new to go so although I have an idea of what is wrong, I don't understand the discordgo documentation enough to know how to fix the problem. 

```
# command-line-arguments
./main.go:96:33: not enough arguments in call to sess.UserGuilds
	have ()
	want (int, string, string)
./main.go:113:20: cannot convert "text" to type discordgo.ChannelType
./main.go:113:20: invalid operation: channel.Type == "text" (mismatched types discordgo.ChannelType and string)
```

ideas?

thanks in advance

**Comment by dhedegaard** [comment]
Hi Spencer,

try again after 74942aa0911f3245df9f387fb82a6fa1e8e3b359 and 944a15ddef8877384efbc25691af090587b1ec56, it seems the discordgo library has made some slight changes to the API since I last used it.
